# Generated by Django 5.2.3 on 2026-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='edad_preferencial',
            field=models.IntegerField(default=60, help_text='Edad mínima para atención preferencial'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='preferencial',
            field=models.BooleanField(default=False, help_text='Atiende preferentemente a tercera edad (60+ años)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='es_preferencial',
            field=models.BooleanField(default=False, help_text='Cliente de atención preferencial (tercera edad)'),
        ),
    ]
