# Generated by Django 5.2.3 on 2026-03-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesa_edad_preferencial_mesa_preferencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del sponsor/logo', max_length=100)),
                ('imagen', models.ImageField(help_text='Imagen del logo (PNG/JPG)', upload_to='logos/')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
            ],
            options={
                'verbose_name': 'Logo Pantalla',
                'verbose_name_plural': 'Logos Pantalla',
                'ordering': ['orden'],
            },
        ),
    ]
