# Generated by Django 5.2.3 on 2026-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logopantalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarquesinaPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Texto a mostrar en la marquesina', max_length=500)),
                ('color', models.CharField(default='#ffffff', help_text='Color del texto (hex, ej: #ffca28)', max_length=20)),
                ('velocidad', models.IntegerField(choices=[(30, 'Lenta'), (20, 'Normal'), (12, 'Rápida'), (8, 'Muy rápida')], default=20, help_text='Duración en segundos del recorrido (menor = más rápido)')),
                ('tamano_fuente', models.CharField(default='1.3rem', help_text='Tamaño de fuente CSS (ej: 1.3rem, 18px, 1.5em)', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marquesina Pantalla',
                'verbose_name_plural': 'Marquesinas Pantalla',
            },
        ),
    ]
