# Generated by Django 5.2.3 on 2026-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marquesinapantalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVideoPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_reproduccion', models.CharField(choices=[('secuencial', 'Secuencial'), ('aleatorio', 'Aleatorio')], default='secuencial', max_length=20)),
                ('volumen', models.IntegerField(default=30, help_text='Volumen del video (0-100)')),
                ('habilitado', models.BooleanField(default=True, help_text='Activar/desactivar el reproductor')),
            ],
            options={
                'verbose_name': 'Configuración Video',
                'verbose_name_plural': 'Configuración Video',
            },
        ),
        migrations.CreateModel(
            name='VideoPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del video', max_length=200)),
                ('url', models.URLField(help_text='URL de YouTube o Vimeo (ej: https://www.youtube.com/watch?v=xxx)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de reproducción (menor = primero)')),
            ],
            options={
                'verbose_name': 'Video Pantalla',
                'verbose_name_plural': 'Videos Pantalla',
                'ordering': ['orden'],
            },
        ),
    ]
