# Generated by Django 5.2.3 on 2026-03-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configvideopantalla_videopantalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigApariencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantalla_fondo', models.CharField(default='#0d1b2a', help_text='Fondo pantalla de llamado', max_length=20)),
                ('pantalla_call_grad1', models.CharField(default='#1565c0', help_text='Gradiente llamado color 1', max_length=20)),
                ('pantalla_call_grad2', models.CharField(default='#0d47a1', help_text='Gradiente llamado color 2', max_length=20)),
                ('pantalla_codigo_color', models.CharField(default='#ffffff', help_text='Color del código de turno', max_length=20)),
                ('pantalla_codigo_fuente', models.CharField(default='Roboto, sans-serif', help_text='Tipografía del código', max_length=100)),
                ('pantalla_codigo_tamano', models.CharField(default='10rem', help_text='Tamaño del código (ej: 10rem)', max_length=20)),
                ('pantalla_nombre_color', models.CharField(default='#ffca28', help_text='Color del nombre del cliente', max_length=20)),
                ('pantalla_nombre_fuente', models.CharField(default='Roboto, sans-serif', help_text='Tipografía del nombre', max_length=100)),
                ('pantalla_nombre_tamano', models.CharField(default='3rem', help_text='Tamaño del nombre', max_length=20)),
                ('pantalla_mesa_color', models.CharField(default='#81d4fa', help_text='Color de la mesa', max_length=20)),
                ('pantalla_mesa_fuente', models.CharField(default='Roboto, sans-serif', help_text='Tipografía de la mesa', max_length=100)),
                ('pantalla_mesa_tamano', models.CharField(default='4rem', help_text='Tamaño de la mesa', max_length=20)),
                ('pantalla_espera_grad1', models.CharField(default='#ff6f00', help_text='Gradiente caja espera color 1', max_length=20)),
                ('pantalla_espera_grad2', models.CharField(default='#ff8f00', help_text='Gradiente caja espera color 2', max_length=20)),
                ('pantalla_historial_codigo', models.CharField(default='#ffca28', help_text='Color código en historial', max_length=20)),
                ('pantalla_historial_nombre', models.CharField(default='#e0e0e0', help_text='Color nombre en historial', max_length=20)),
                ('pantalla_historial_mesa', models.CharField(default='#81d4fa', help_text='Color mesa en historial', max_length=20)),
                ('nav_grad1', models.CharField(default='#1565c0', help_text='Gradiente navbar color 1', max_length=20)),
                ('nav_grad2', models.CharField(default='#0d47a1', help_text='Gradiente navbar color 2', max_length=20)),
                ('totem_fondo_grad1', models.CharField(default='#0d47a1', help_text='Gradiente fondo totem color 1', max_length=20)),
                ('totem_fondo_grad2', models.CharField(default='#1565c0', help_text='Gradiente fondo totem color 2', max_length=20)),
                ('totem_fondo_grad3', models.CharField(default='#1e88e5', help_text='Gradiente fondo totem color 3', max_length=20)),
                ('totem_header_grad1', models.CharField(default='#ff6f00', help_text='Gradiente header totem color 1', max_length=20)),
                ('totem_header_grad2', models.CharField(default='#ff8f00', help_text='Gradiente header totem color 2', max_length=20)),
                ('btn_llamar_grad1', models.CharField(default='#ff6f00', help_text='Botón llamar color 1', max_length=20)),
                ('btn_llamar_grad2', models.CharField(default='#ff8f00', help_text='Botón llamar color 2', max_length=20)),
                ('btn_completar_grad1', models.CharField(default='#2e7d32', help_text='Botón completar color 1', max_length=20)),
                ('btn_completar_grad2', models.CharField(default='#43a047', help_text='Botón completar color 2', max_length=20)),
                ('btn_guardar_grad1', models.CharField(default='#1565c0', help_text='Botón guardar color 1', max_length=20)),
                ('btn_guardar_grad2', models.CharField(default='#1e88e5', help_text='Botón guardar color 2', max_length=20)),
                ('confirmado_esperando_grad1', models.CharField(default='#2e7d32', help_text='Fondo esperando color 1', max_length=20)),
                ('confirmado_esperando_grad2', models.CharField(default='#43a047', help_text='Fondo esperando color 2', max_length=20)),
                ('confirmado_llamado_grad1', models.CharField(default='#e65100', help_text='Fondo llamado color 1', max_length=20)),
                ('confirmado_llamado_grad2', models.CharField(default='#ff6f00', help_text='Fondo llamado color 2', max_length=20)),
                ('confirmado_completado_grad1', models.CharField(default='#1565c0', help_text='Fondo completado color 1', max_length=20)),
                ('confirmado_completado_grad2', models.CharField(default='#1e88e5', help_text='Fondo completado color 2', max_length=20)),
                ('confirmado_cancelado_grad1', models.CharField(default='#b71c1c', help_text='Fondo cancelado color 1', max_length=20)),
                ('confirmado_cancelado_grad2', models.CharField(default='#e53935', help_text='Fondo cancelado color 2', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración Apariencia',
                'verbose_name_plural': 'Configuración Apariencia',
            },
        ),
    ]
