# Generated by Django 5.2.3 on 2026-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configapariencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marquesinapantalla',
            options={'ordering': ['orden'], 'verbose_name': 'Marquesina Pantalla', 'verbose_name_plural': 'Marquesinas Pantalla'},
        ),
        migrations.AddField(
            model_name='marquesinapantalla',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)'),
        ),
    ]
