# Generated by Django 5.2.3 on 2026-03-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_marquesinapantalla_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo_preferencial',
            field=models.CharField(blank=True, default='', help_text='Motivo: edad, solicitud, o vacío', max_length=30),
        ),
        migrations.AlterField(
            model_name='turno',
            name='es_preferencial',
            field=models.BooleanField(default=False, help_text='Cliente de atención preferencial'),
        ),
    ]
