# Generated by Django 5.2.3 on 2026-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_turno_motivo_preferencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configapariencia',
            name='pantalla_footer_texto',
            field=models.CharField(default='Powered by TotemIA 2026', help_text='Texto del footer en la pantalla de llamado', max_length=200),
        ),
    ]
